// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/leoseiji/go-clean-architecture/internal/entity"
	"github.com/leoseiji/go-clean-architecture/internal/infra/database"
	"github.com/leoseiji/go-clean-architecture/internal/infra/web"
	"github.com/leoseiji/go-clean-architecture/internal/usecase"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository)
	return createOrderUseCase
}

func NewListOrderUseCase(db *sql.DB) *usecase.ListOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	listOrderUseCase := usecase.NewListOrderUseCase(orderRepository)
	return listOrderUseCase
}

func NewWebOrderHandler(db *sql.DB) *web.WebOrderHandler {
	orderRepository := database.NewOrderRepository(db)
	webOrderHandler := web.NewWebOrderHandler(orderRepository)
	return webOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))
